project:
  type: website
  output-dir: ./website/_site  # Where Quarto places the rendered site
  
bibliography: ./resources/references.bib

metadata-files:
  - _metadata.yml

website:
  title: "Physics 360: Modern Astrophysics"
  navbar:
  # Global navigation bar for the website
    left:
      - text: "Lectures"
        menu:
          - text: "Lecture 1"
            href: ./lectures/lecture1.qmd
          - text: "Lecture 2"
            href: ./lectures/lecture2.qmd
      - text: "Assignments"
        href: ../assignments/
      - text: "Final Project"
        menu:
          - text: "Project Suggestions"
            href: ./final_project/project_ideas.qmd
      - text: "Resources"
        href: resources.qmd

format:
  html:
    css: styles.css
