project:
  type: website
  output-dir: ./website/_site  # Where Quarto places the rendered site
  
bibliography: ./resources/references.bib

metadata-files:
  - _metadata.yml

website:
  title: "Physics 360: Modern Astrophysics"
  navbar:
  # Global navigation bar for the website
    left:
      - text: "Home"
        href: ./website/index.qmd
      - text: "Lectures"
        menu:
          - text: "Preliminaries"
            href: ./lectures/preliminaries.qmd
          - text: "Gravity"
            href: ./lectures/gravity.qmd
      - text: "Tutorials"
        menu:
          - text: "Setup python"
            href: ./tutorials/python_setup.qmd
          - text: "gala tutorial"
            href: ./tutorials/gala_tutorial.qmd
      - text: "Assignments"
        menu:
          - text: "Workflow"
            href: ./assignments/assignment_1.qmd
      - text: "Final Project"
        menu:
          - text: "Project Suggestions"
            href: ./final_project/project_ideas.qmd
#      - text: "Resources"
#        href: resources.qmd

format:
  html:
    css: styles.css
